# Generated by Django 3.1.2 on 2023-05-08 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('allergies', models.TextField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_profile',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=50)),
                ('org_bio', models.CharField(max_length=50)),
                ('org_memberrequests', models.ManyToManyField(related_name='membership_requested_organizations', through='userprofile.MembershipRequest', to='userprofile.StudentProfile')),
                ('org_members', models.ManyToManyField(related_name='member_organizations', through='userprofile.Membership', to='userprofile.StudentProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_profile',
            },
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='userprofile.organizationprofile'),
        ),
        migrations.AddField(
            model_name='membershiprequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='userprofile.studentprofile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='userprofile.organizationprofile'),
        ),
        migrations.AddField(
            model_name='membership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='userprofile.studentprofile'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
                ('event_desc', models.CharField(max_length=200)),
                ('event_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('event_datetime', models.DateTimeField()),
                ('event_release', models.DateTimeField()),
                ('event_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='userprofile.organizationprofile')),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
