# Generated by Django 3.1.2 on 2023-05-12 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20230511_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_release',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='event',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='release_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets_left',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_bought', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='userprofile.event')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='userprofile.studentprofile')),
            ],
        ),
    ]
