# Generated by Django 4.2.1 on 2023-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_membership_id_alter_membershiprequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_tickets',
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_left',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
