# Generated by Django 4.2.1 on 2023-05-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_alter_membership_id_alter_membershiprequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
