# Generated by Django 4.2.1 on 2023-05-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_event_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='drinkpref',
            field=models.CharField(choices=[('Öl & Vitt vin', 'Öl & Vitt vin'), ('Öl & Rött vin', 'Öl & Rött vin'), ('Cider & Vitt vin', 'Cider & Vitt vin'), ('Cider & Rött vin', 'Cider & Rött vin'), ('Alkoholfritt', 'Alkoholfritt')], default='Alkoholfritt', max_length=50),
        ),
    ]
