# Generated by Django 4.2.1 on 2023-05-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0016_studentprofile_drinkpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.CharField(choices=[('Fin fest 1', 'Fin fest 1'), ('Fin fest 2', 'Fin fest 2'), ('Ful fest 1', 'Ful fest 1'), ('Ful fest 2', 'Ful fest 2'), ('Företag 1', 'Företag 1'), ('Företag 2', 'Företag 2'), ('Sport 1', 'Sport 1'), ('Sport 2', 'Sport 2')], default='Fin fest 1', max_length=50),
        ),
    ]
