# Generated by Django 4.2.1 on 2023-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0018_alter_event_event_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_pic',
        ),
    ]
