# Generated by Django 4.2.1 on 2023-05-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0019_remove_event_event_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.IntegerField(default=0),
        ),
    ]
