# Generated by Django 4.2.1 on 2023-05-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0021_alter_event_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
