# Generated by Django 4.2.1 on 2023-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0022_alter_event_event_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='drinkpref',
            field=models.CharField(choices=[('Beer & White wine', 'Beer & White wine'), ('Beer & Red wine', 'Beer & Red wine'), ('Cider & White wine', 'Cider & White wine'), ('Cider & Red wine', 'Cider & Red wine'), ('Non-alcoholic', 'Non-alcoholic')], default='Alkoholfritt', max_length=50),
        ),
    ]
