# Generated by Django 3.1.2 on 2023-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0023_alter_studentprofile_drinkpref'),
        ('userprofile', '0023_auto_20230520_1619'),
    ]

    operations = [
    ]
