# Generated by Django 3.1.2 on 2023-05-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0027_auto_20230526_1318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='membershiprequest',
            unique_together={('organization', 'student')},
        ),
    ]
